---
# tasks file for apache
- name: Install apache
  yum: name=httpd state=present

- name: set Apache reverse proxy configuration
  template: src=../templates/apache_reverse_proxy.conf dest=/etc/httpd/conf/httpd.conf

- name: Apache restart
  service: name=httpd state=restarted