---
#rundeck.yml calls the main.yml task file to do all necessary tasks to install and configure Rundeck
- name: Install Rundeck
  hosts: rundeck
  tasks:
  - name: Install Rundeck
    include: roles/rundeck/tasks/main.yml
