---
#apache.yml calls the main.yml task file to do all necessary tasks to install and configure Rundeck
- name: Install apache
  hosts: tomcat-server
  become: True
  become_method: sudo
  tasks:
  - name: Install Tomcat
    include: roles/tomcat/tasks/main.yml