---
  - name: install packages
    yum: 
      name: "{{ item }}"
      state: installed
    with_items:
      - java-1.8.0
      - http://repo.rundeck.org/latest.rpm
      - libsemanage-python

  - name: install rundeck
    yum:
      name: rundeck
      state: installed

  - name: set rundeck to be enabled at boot and start it
    systemd:
      name: rundeckd
      enabled: yes
      state: started
      daemon_reload: yes

  - name: wait for rundeck to be started
    wait_for:
      timeout: 300

  - name: install rundeck cli
    shell: '{{ item }}'
    with_items:
      - sudo wget https://bintray.com/rundeck/rundeck-rpm/rpm -O bintray.repo
      - sudo mv bintray.repo /etc/yum.repos.d/
      - sudo yum install -y rundeck-cli

  - name: set firewalld to be enabled at boot and start it
    systemd:
      name: firewalld
      enabled: yes
      state: started

  - name: enable https port in the firewall
    firewalld:
      port: 4440/tcp
      state: enabled
      permanent: yes
      immediate: yes

  - name: set seboolean httpd to allow network connections
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Create a rundeck project
    shell: rd projects create -p monitoring
    environment:
      RD_URL: http://192.168.100.21:4440/
      RD_USER: admin
      RD_PASSWORD: admin
    ignore_errors: yes

  - name: export rundeck password
    copy: src=../files/rundeck.password  dest=/tmp/rundeck.password

  - name: Add rundeck key
    shell: rd keys create -f /tmp/rundeck.password -t password -p keys/rundeck.password
    environment:
      RD_URL: http://192.168.100.21:4440/
      RD_USER: admin
      RD_PASSWORD: admin
    ignore_errors: yes
    

  - name: configure rundeck project
    template: src=../templates/project.properties dest=/var/rundeck/projects/monitoring/etc/project.properties

  - name: create settings file for nodes
    template: src=../templates/ressource.xml dest=/var/rundeck/projects/monitoring/etc/ressource.xml
  
  - name: ansible create directory example
    file:
      path: /var/lib/rundeck/var/storage/content/keys
      state: directory

  - name: configure rundeck job
    template: src=../templates/jobs.xml dest=/tmp/jobs.xml

  - name: load rundeck job
    shell: "rd jobs load -p monitoring --file /tmp/jobs.xml"
    environment:
      RD_URL: http://192.168.100.21:4440/
      RD_USER: admin
      RD_PASSWORD: admin
    ignore_errors: yes

  - name: restart rundeck
    service: name=rundeckd state=restarted